apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-prometheus
spec:
  selector:
    matchLabels:
      app: spring-boot-prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-boot-prometheus
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: spring-boot-prometheus
          image: log-metrics-emitter:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 294Mi














#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: metrics
#spec:
#  selector:
#    matchLabels:
#      app: metrics
#  replicas: 1
#  template:
#    metadata:
#      labels:
#        app: metrics
#    spec:
#      containers:
#        - name: metrics
#          image: metrics:latest
#          imagePullPolicy: Never
#          ports:
#            - containerPort: 8080