apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-boot-prometheus
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: spring-boot-prometheus
  endpoints:
    - port: api
      path: '/metrics'
      interval: 10s
      honorLabels: true